import { Open_Sans, Source_Code_Pro } from "next/font/google"; // Import fonts from Google
import "./globals.css";
import Navbar from "./components/Navbar";


export const metadata = {
  title: "CP_Clone",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`$antialiased`}>
        <Navbar />
        {children}
      </body>
    </html>
  );
}
